set tabstop=2       " number of visual spaces per TAB
set softtabstop=2   " number of spaces in tab when editing
set shiftwidth=2    " number of spaces to use for autoindent
set expandtab       " tabs are spaces
filetype indent on  " load filetype-specific indent files

autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2 " default to 2 char indentation for Ruby

set number          " show line numbers
set showcmd         " show command in bottom bar
set cursorline      " highlight current line
set wildmenu        " visual autocomplete for command menu
set lazyredraw      " redraw only when we need to
set showmatch       " highlight matching brackets

set incsearch  " incremental search highlighting
set ignorecase " case-insensitive search
set smartcase  " switch to case-sensitive search when uppercase letters entered

syntax enable
set background=dark
colorscheme gruvbox

" Load plugins
source ~/dotfiles/.vim/vim-plug

" Keyboard shortcuts

" Ctrl-S to save file
noremap <M-s> :update<CR> 

