set tabstop=2       " number of visual spaces per TAB
set softtabstop=2   " number of spaces in tab when editing
set expandtab       " tabs are spaces
filetype indent on  " load filetype-specific indent files

set number          " show line numbers
set showcmd         " show command in bottom bar
set cursorline      " highlight current line
set wildmenu        " visual autocomplete for command menu
set lazyredraw      " redraw only when we need to
set showmatch       " highlight matching brackets

set incsearch  " incremental search highlighting
set ignorecase " case-insensitive search
set smartcase  " switch to case-sensitive search when uppercase letters entered

syntax enable
set background=dark
colorscheme gruvbox

source ~/dotfiles/.vim/vim-plug
