export PATH=$PATH:~/dotfiles/bin
export EDITOR=nvim

# Shell integrations
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source "$HOME/.asdf/asdf.sh"
source <(fzf --zsh)

# Command history
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

# Completion
autoload -U compinit && compinit
zmodload -i zsh/complist

# Keyboard bindings
bindkey -e
bindkey "^b" backward-word
bindkey "^f" forward-word

# Aliases
alias l="eza -T --level=1 --group-directories-first"
alias ll="l --long"
alias la="l --all --level=1"
alias t="l --all -I .git"
alias t2="t --level=2"
alias t3="t --level=3"
alias cd="z"
alias old_branches="git branch -vv | grep 'origin/.*: gone]' | awk '{print \$1}'"

alias gs="git status --short"
alias gl="git log --all --graph --pretty=format:'%C(magenta)%h %C(white) %an %ar%C(auto) %D%n%s%n'"
alias gd="git diff"
alias gp="git push"
alias gu="git pull"
alias vi=nvim
alias vim=nvim
