# Environment

export PATH=~/tcc/aws-inf/scripts/utils:$PATH
export LANG="en_GB.UTF-8"
export EDITOR=vim

# Completion

autoload -Uz compinit && compinit

# Matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Keyboard bindings

bindkey -e

# Aliases

alias l="ls -l"
alias la="ls -la"

# History

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt HIST_EXPIRE_DUPS_FIRST

# Color

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

# Asdf version manager
source /usr/local/opt/asdf/asdf.sh
source /usr/local/etc/bash_completion.d/asdf.bash

# Load local config

if [ -f "${HOME}/.localrc" ]; then
  source "${HOME}/.localrc"
fi

### Added by Zplugin's installer
source ~/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

zplugin light mafredri/zsh-async
zplugin light sindresorhus/pure

